### ISSUE TITLE
$d is undefined in virtual_feature.pl line 121

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-dav#1]
In this line:

```
       if (!$d->{'parent'} &&
```

https://github.com/virtualmin/virtualmin-dav/blob/master/virtual_feature.pl#L121

$d is undefined. It looks like it should be $_[0], though that's ugly, and I'm gonna refactor it to put the argument into $d.

So, unless you tell me I'm misreading this, I'm gonna check in a change that does:

```
my ($d) = unshift;
```

(At least, I think that's the right way to get a hash ref into $d?)

And, changes all of the $_[0]->whatever mentions to $d->. That make sense to do?

**Comment by jcameron** [comment]
Yes, that sounds like the correct fix to me.
