### ISSUE TITLE
$port is undefined in virtual_feature.pl

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-dav#2]
In this line in the feature_validate function:

```
my ($virt, $vconf) = &virtual_server::get_apache_virtual($d->{'dom'}, $port);
```

https://github.com/virtualmin/virtualmin-dav/blob/master/virtual_feature.pl#L313

$port is undefined. I see examples of $port being passed into functions, and I see examples of that call without $port. To keep the current behavior, we'd just knock off the $port in that call...but, if there's actually supposed to be port specificity there, that'd be wrong (but we've been doing it wrong for years since it's never been defined). So, I'm gonna delete $port in that call.

If that's wrong, lemme know, and I'll dig further, and figure out where we need to pull $port from for this to make sense.

**Comment by jcameron** [comment]
Did you already remove the `$port` reference? I don't see it in the latest code.

**Comment by virtualmin** [comment]
I did. Should it be there? I'm not sure where to get it from, if it should.

**Comment by jcameron** [comment]
No, it's not needed in this case (the port defaults to 80).
