### ISSUE TITLE
%u is undefined and unused in virtual_feature.pl

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-dav#3]
In the feature_modify function, there's this bit of no-op code. It's code that seems like it _wants_ to do something, but because %u gets thrown away, it's seemingly doing nothing, unless there's side effects in there that I don't understand.

```
        foreach my $e (@users) {
                $u->{'dom'} = $_[0]->{'dom'};
                $u->{'user'} =~ s/$_[1]->{'dom'}/$_[0]->{'dom'}/;
                }
        &save_users($_[0], \@users);
```

It looks like $e should be $u. Though this is also a little confusing...I guess @users is an array of refs, and so putting something into $u->{'dom'} actually updates within @users?

Anyway, I'm gonna change $e to $u, and hope my understanding of hash refs in an array like this is right.

**Comment by swelljoe** [comment]
Pretty sure this one is fixed. At least, it doesn't seem to have broken anything obvious.

**Comment by jcameron** [comment]
Yes, it should be `$u` and not `$e` in the foreach
